In [1]:
import cv2
import numpy as np

img = cv2.imread('image.jpg')
# Загрузка изображения
# Метод imread загружает изображение в формате BGR (не RGB!)

rows, cols = img.shape[:2]
# Получаем размеры изображения (количество строк и столбцов)
# img.shape возвращает кортеж (height, width, channels), нам нужны только height и width

# Поворот на 45 градусов

rotation_matrix = cv2.getRotationMatrix2D((cols/2, rows/2), 45, 1)
rotated_img = cv2.warpAffine(img, rotation_matrix, (cols, rows))
# Создаем матрицу поворота для вращения изображения на 45 градусов
# Аргументы функции getRotationMatrix2D():
# ((cols/2, rows/2)) - точка вращения (центр изображения)
# 45 - угол поворота в градусах (положительное значение - поворот против часовой стрелки)
# 1 - коэффициент масштабирования (1 означает сохранение оригинального размера)
# Применяем аффинное преобразование (вращение) к изображению
# warpAffine выполняет поворот изображения с использованием полученной матрицы поворота
# Третий аргумент (cols, rows) задает размер выходного изображения
rotated_img = cv2.warpAffine(img, rotation_matrix, (cols, rows))


# Рисуем фигуры
cv2.circle(rotated_img, (100, 100), 50, (0, 0, 255), -1)  # Красный круг


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(191, 264, 3), dtype=uint8)

In [2]:
cv2.rectangle(rotated_img, (200, 200), (300, 300), (0, 255, 0), 3)  # Зеленый прямоугольник

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(191, 264, 3), dtype=uint8)

In [3]:
img


array([[[ 43,  96,  93],
        [ 47, 100,  97],
        [ 54, 103, 101],
        ...,
        [ 34,  55,  52],
        [ 33,  54,  51],
        [ 15,  36,  33]],

       [[ 32,  82,  80],
        [ 43,  93,  91],
        [ 38,  85,  83],
        ...,
        [ 26,  47,  44],
        [ 34,  55,  52],
        [ 28,  49,  46]],

       [[ 20,  67,  65],
        [ 42,  89,  87],
        [ 23,  65,  64],
        ...,
        [ 21,  42,  39],
        [ 30,  49,  46],
        [ 34,  53,  50]],

       ...,

       [[240, 240, 240],
        [240, 240, 240],
        [240, 240, 240],
        ...,
        [232, 232, 232],
        [232, 232, 232],
        [232, 232, 232]],

       [[241, 241, 241],
        [241, 241, 241],
        [241, 241, 241],
        ...,
        [232, 232, 232],
        [231, 231, 231],
        [231, 231, 231]],

       [[242, 242, 242],
        [242, 242, 242],
        [242, 242, 242],
        ...,
        [231, 231, 231],
        [229, 229, 229],
        [229, 229, 229]]

In [4]:
cv2.putText(rotated_img, 'Hello!', (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(191, 264, 3), dtype=uint8)

In [5]:
cv2.imwrite('output.jpg', rotated_img)

True

In [25]:
import cv2
import numpy as np


img = cv2.imread("tree_winter.jpg")
h, w = img.shape[:2]


flipped = cv2.flip(img, 1)

cv2.circle(flipped, (w-100, 100), 60, (0, 215, 255), -1)

for i in range(2000):
    x = np.random.randint(0, w)
    y = np.random.randint(0, h)
    flipped[y, x] = (255, 255, 255)

cv2.putText(flipped, "Happy Winter!", (10, h-20),
            cv2.FONT_HERSHEY_SIMPLEX, 2,
            (0, 0, 255), 4)


cv2.circle(flipped, (200, 300), 40, (0, 255, 0), -1)
cv2.putText(flipped, "NEW YEAR", (150, 305),
            cv2.FONT_HERSHEY_SIMPLEX, 0.5,
            (255, 255, 255), 1)


cv2.imwrite("new_year_tree.jpg", flipped)

cv2.imshow("Original", img)
cv2.imshow("New Year", flipped)
cv2.waitKey(0)


-1

In [26]:
import cv2
import numpy as np


img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))

summed_img = cv2.addWeighted(img1, 0.5, img2, 0.5, 0)


In [29]:
mean = 0
var = 0
sigma = var ** 0.5
noise = np.random.normal(mean, sigma, summed_img.shape).astype(np.uint8)
noisy_img = cv2.add(summed_img, noise)


In [31]:

cv2.imshow('Noisy Summed Image', noisy_img)
cv2.waitKey(0)


-1

In [ ]:
import cv2
import numpy as np

img = cv2.imread("house.jpg")
h, w = img.shape[:2]


hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
hsv[:, :, 1] = hsv[:, :, 1] * 0.5
hsv[:, :, 2] = hsv[:, :, 2] * 0.9
faded = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

#Виньетка
kernel_x = cv2.getGaussianKernel(w, w/3)
kernel_y = cv2.getGaussianKernel(h, h/3)
mask = kernel_y * kernel_x.T
mask = mask / mask.max()
vignette = np.copy(faded)

for i in range(3):
    vignette[:, :, i] = vignette[:, :, i] * mask

# Зерно
noise = np.random.normal(0, 10, vignette.shape).astype(np.uint8)
grain = cv2.add(vignette, noise)

#  Царапины
for i in range(10):
    x1 = np.random.randint(0, w)
    x2 = np.random.randint(0, w)
    cv2.line(grain, (x1, 0), (x2, h), (255,255,255), 1)

#  Осветление центра
center_mask = mask
for i in range(3):
    grain[:, :, i] = grain[:, :, i] + (center_mask*30).astype(np.uint8)

# Сохранение и показ
cv2.imwrite("old_photo.jpg", grain)

cv2.imshow("Original", img)
cv2.imshow("Old Photo", grain)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2

# Загружаем зашумлённое изображение
noisy_img = cv2.imread('old_photo.jpg')

# Применяем усредняющий фильтр
blur = cv2.blur(noisy_img, (5, 5))
kernel = np.ones((3,3), np.uint8)
eroded = cv2.erode(blur, kernel, iterations = 1)
restored = cv2.dilate(blur, kernel, iterations = 1)
# Показываем результат
cv2.imshow("Original", noisy_img)
cv2.imshow("Restored", restored)
cv2.waitKey(0)


-1